package domain

import "time"

type AttendanceStatus string

const (
	AttendanceStatusPresent AttendanceStatus = "present"
	AttendanceStatusAbsent  AttendanceStatus = "absent"
	AttendanceStatusLate    AttendanceStatus = "late"
	AttendanceStatusExcused AttendanceStatus = "excused"
)

type Attendance struct {
	// ID generated by DB
	ID         string           `db:"id"`
	StudentID  string           `db:"student_id"`
	ModuleID   string           `db:"module_id"`
	Status     AttendanceStatus `db:"status"`
	RecordedAt time.Time        `db:"recorded_at"`
	Notes      string           `db:"notes"`
}
