package domain

import "time"

type Course struct {
	// ID generated by DB
	ID          string    `db:"id"`
	TeacherID   string    `db:"teacher_id"`
	Name        string    `db:"name"`
	Description string    `db:"description"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}
