package domain

import "time"

// type FileType string
//
// const (
// 	FileTypeImagePng  FileType = "image/png"
// 	FileTypeImageJpg  FileType = "image/jpg"
// 	FileTypeImageGif  FileType = "image/gif"
// 	FileTypeImageWebp FileType = "image/webp"
//
// 	FileTypeVideoMp4 FileType = "video/mp4"
// )

type ModuleContentType string

const (
	ModuleContentTypeLesson     ModuleContentType = "lesson"
	ModuleContentTypeAssignment ModuleContentType = "assignment"
)

type Module struct {
	// ID generated by DB
	ID       string  `db:"id"`
	CourseID string  `db:"course_id"`
	Name     string  `db:"name"`
	Position float64 `db:"position"`
	// Default False
	IsPusblished bool `db:"is_published"`
	// Default NULL
	UnlockDate *time.Time `db:"unlock_date"`
	// Default Now
	CreatedAt time.Time `db:"created_at"`
	// Default Now
	UpdatedAt time.Time `db:"updated_at"`
}

type ModuleContent struct {
	// ID generated by DB
	ID                string            `db:"id"`
	ModuleID          string            `db:"module_id"`
	Title             string            `db:"title"`
	ModuleContentType ModuleContentType `db:"type"`
	BodyContent       string            `db:"body_content"`
	Position          float64           `db:"position"`
	// Default False
	IsPublished bool `db:"is_published"`
	// Default Now
	CreatedAt time.Time `db:"created_at"`
	// Default Now
	UpdatedAt time.Time `db:"updated_at"`
}

type ContentAttachment struct {
	ID              string `db:"id"`
	ModuleContentID string `db:"module_content_id"`
	Name            string `db:"name"`
	URL             string `db:"url"`
	SizeBytes       int64  `db:"size_bytes"`
	FileType        string `db:"type"`

	CreatedAt time.Time `db:"created_at"`
}
