DROP TABLE IF EXISTS admin;

DROP TABLE IF EXISTS student;

DROP TABLE IF EXISTS parent;

DROP TABLE IF EXISTS teacher;

DROP INDEX IF EXISTS idx_user_role ON "user"(role);

DROP TABLE IF EXISTS "user";

DROP IF EXISTS TYPE user_role;
