// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockStorage
func (_mock *MockStorage) Delete(ctx context.Context, filename string) error {
	ret := _mock.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockStorage_Expecter) Delete(ctx any, filename any) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, filename)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, filename string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(err error) *MockStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, filename string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetUrl provides a mock function for the type MockStorage
func (_mock *MockStorage) GetUrl(ctx context.Context, filename string) (string, error) {
	ret := _mock.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUrl'
type MockStorage_GetUrl_Call struct {
	*mock.Call
}

// GetUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockStorage_Expecter) GetUrl(ctx any, filename any) *MockStorage_GetUrl_Call {
	return &MockStorage_GetUrl_Call{Call: _e.mock.On("GetUrl", ctx, filename)}
}

func (_c *MockStorage_GetUrl_Call) Run(run func(ctx context.Context, filename string)) *MockStorage_GetUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetUrl_Call) Return(s string, err error) *MockStorage_GetUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_GetUrl_Call) RunAndReturn(run func(ctx context.Context, filename string) (string, error)) *MockStorage_GetUrl_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockStorage
func (_mock *MockStorage) Upload(ctx context.Context, filename string, content io.Reader, size int64, contentType string) (string, error) {
	ret := _mock.Called(ctx, filename, content, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) (string, error)); ok {
		return returnFunc(ctx, filename, content, size, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) string); ok {
		r0 = returnFunc(ctx, filename, content, size, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r1 = returnFunc(ctx, filename, content, size, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
//   - content io.Reader
//   - size int64
//   - contentType string
func (_e *MockStorage_Expecter) Upload(ctx any, filename any, content any, size any, contentType any) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, filename, content, size, contentType)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, filename string, content io.Reader, size int64, contentType string)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(s string, err error) *MockStorage_Upload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(ctx context.Context, filename string, content io.Reader, size int64, contentType string) (string, error)) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}
